---

- name: Set CPU priority for agent processes
  ansible.windows.win_regedit:
    path: "HKLM:\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Image File Execution Options\\{{ item }}\\PerfOptions"
    name: CpuPriorityClass
    data: "{{ prom_windows_exporter_process_priority }}"
    type: dword
  loop:
    - windows_exporter.exe
    - prometheus.exe
  notify:
    - Restart windows_exporter
    - Restart Prometheus

- name: Create textfile collector directory
  ansible.windows.win_file:
    path: "{{ prom_windows_exporter_textfile_dir }}"
    state: directory

- name: Create scripts directory
  ansible.windows.win_file:
    path: "{{ prom_windows_exporter_script_dir }}"
    state: directory

- name: Land custom scripts
  ansible.windows.win_copy:
    src: "{{ prom_windows_exporter_script_dir_local }}/{{ item.file }}"
    dest: "{{ prom_windows_exporter_script_dir }}\\"
  loop: "{{ prom_windows_exporter_scripts }}"

- name: Create scheduled tasks
  community.windows.win_scheduled_task:
    name: "Prometheus Custom Script - {{ item.file }}"
    logon_type: service_account
    user: LOCAL SERVICE
    actions:
      - path: powershell
        arguments: "-File \"{{ prom_windows_exporter_script_dir }}\\{{ item.file }}\""
        working_directory: "{{ prom_windows_exporter_textfile_dir }}"
    triggers:
      - type: registration
        repetition:
          interval: "PT{{ item.interval_minutes }}M"
  loop: "{{ prom_windows_exporter_scripts }}"

- name: Land windows_exporter config
  ansible.windows.win_template:
    src: windows_exporter.yml.j2
    dest: "{{ prom_windows_exporter_config_file }}"
  notify: Restart windows_exporter
  tags:
    - configure

- name: Land Prometheus config
  ansible.windows.win_template:
    src: prometheus.yml.j2
    dest: "{{ prom_agent_config_file }}"
  notify: Restart Prometheus
  tags:
    - configure
