---
# tasks file for prometheus_windows
- fail:
    msg: The "prom_remote_write_token" var must be provided
  when: (prom_remote_write_token is not defined) or (prom_remote_write_token|length == 0)
  tags:
    - configure

- include_tasks: install.yml
  tags:
    - install

- include_tasks: configure.yml
  tags:
    - configure