---
# tasks file for prometheus_windows

- name: Ensure token is provided for each remote write endpoint
  assert:
    that: ('token' in item) and (item['token']|length > 0)
    fail_msg: The "token" var must be provided for each remote write endpoint
  loop: "{{ prom_remote_write_endpoints }}"
  no_log: true
  tags:
    - configure

- include_tasks: install.yml
  tags:
    - install

- include_tasks: configure.yml
  tags:
    - configure