---
# tasks file for prometheus_windows

- fail:
    msg: The "token" var must be provided for each remote write endpoint
  when: ('token' not in item) or (item['token']|length == 0)
  loop: "{{ prom_remote_write_endpoints }}"
  tags:
    - configure

- include_tasks: install.yml
  tags:
    - install

- include_tasks: configure.yml
  tags:
    - configure