---
- name: Download Windows installer locally
  delegate_to: localhost
  get_url: 
    url: "{{ prom_windows_exporter_installer }}"
    dest: "/tmp/windows_exporter.msi"
  when: localdownload | bool

- name: Create windows_exporter data directory
  ansible.windows.win_file:
    path: "{{ prom_windows_exporter_data_dir }}"
    state: directory

- name: Copy Windows installer
  win_copy: 
    src: "/tmp/windows_exporter.msi"
    dest: "{{ prom_windows_exporter_msi_path }}"
  when: localdownload | bool

- name: Install the Windows exporter
  win_package:
    path: "{{ prom_windows_exporter_msi_path }}"
  when: localdownload | bool

- name: Install the Windows exporter
  win_package:
    path: "{{ prom_windows_exporter_installer }}"
    product_id: windows_exporter
  when: not localdownload  | bool

- name: Create textfile collector directory
  ansible.windows.win_file:
    path: "{{ prom_windows_exporter_textfile_dir }}"
    state: directory

- name: Land windows_exporter config
  win_template:
    src: windows_exporter.yml.j2
    dest: "{{ prom_windows_exporter_config_file }}"

- name: Ensure service is started
  win_service:
    name: windows_exporter
    start_mode: auto
    state: started
    path: '"C:\Program Files\windows_exporter\windows_exporter.exe" --config.file "{{ prom_windows_exporter_config_file }}"'